name       : podman
version    : 1.7.0
release    : 4
source     :
    - git|https://github.com/containers/libpod : v1.7.0
extract    : no
license    : Apache-2.0
homepage   : https://podman.io/
component  : virt
summary    : A daemonless container engine for developing, managing, and running Open Container Initiative (OCI) containers and container images.
description: |
    Containers under the control of Podman can either be run by root or by a non-privileged user. Podman manages the entire container ecosystem which includes pods, containers, container images, and container volumes using the libpod library. Podman specializes in all of the commands and functions that help you to maintain and modify OCI container images, such as pulling and tagging. It allows you to create, run, and maintain those containers created from those images in a production environment.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gpgme)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(libseccomp)
    - pkgconfig(libselinux)
    - pkgconfig(ostree-1)
    - btrfs-progs-devel
    - golang
    - go-md2man
rundeps    :
    - cni-plugins
    - conmon
    - iptables
    - skopeo
    - slirp4netns
environment: |
    export GOPATH=$PKG_BUILD_DIR
    export SRC_DIR=$GOPATH/src/github.com/containers/libpod
    export BUILDTAGS="ostree seccomp systemd varlink containers_image_ostree_stub"

    # buildsystem passes LDFLAGS to GO's -ldflags, which isn't really compatible
    unset LDFLAGS
setup      : |
    mkdir -p $SRC_DIR
    cp -r $sources/libpod.git/. $SRC_DIR/
build      : |
    %make -C $SRC_DIR BUILDTAGS="$BUILDTAGS"
install    : |
    %make_install install.completions install.config -C $SRC_DIR \
        PREFIX=%PREFIX% \
        TMPFILESDIR=%libdir%/tmpfiles.d \
        SYSTEMDDIR=%libdir%/systemd/system \
        USERSYSTEMDDIR=%libdir%/systemd/user
